DATALOADER:
  TRAIN_X:
    SAMPLER: "RandomDomainSampler"
    BATCH_SIZE: 3
  TEST:
    BATCH_SIZE: 3

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 40
  LR_SCHEDULER: "cosine"

TRAINER:
  DAELDG:
    STRONG_TRANSFORMS: ["random_flip", "cutout", "randaugment2", "normalize"]